### ISSUE TITLE
Melhorar resumo de horas

### ISSUE THREAD

**Issue by Viperized** [camponez/importescala#15]
Listar além da horas de voo totais e faixa 1 e 2, somar as horas de sobreaviso separadas, as de reserva separadas, e criar uma nova soma de "horas totais pagamento". 

Nesse caso, necessário usar somente 1/3 das horas de sobreaviso.

Por exemplo, se fiz apenas um sobreaviso de 12 horas, na soma total pagamento utilizar apenas 4 horas para o sobreaviso.

**Comment by camponez** [comment]
Fixed: 668c80c23346948de6
