### ISSUE TITLE
Data incorreta de evento de voo na versão 1.26

### ISSUE THREAD

**Issue by Viperized** [camponez/importescala#6]
XML:

```xml
<ActivityDate>05/01/2015 02:35:00</ActivityDate>
   <Category>FO</Category>
   <Base>BHZ</Base>
   <Request />
   <STD>02:55</STD>
   <STA>00:35</STA>
   <Actype>E90</Actype>
   <FlightNo>9472</FlightNo>
   <Origin>SJP</Origin>
   <Destination>SSA</Destination>
```

CSV gerado:

```csv
Voo SJP-SSA AD9472,04/01/2015,00:35,04/01/2015,02:55,False,"Aeroporto de São José do Rio Preto",Horas de voo: 2:20
```

O correto seria dia 05/01/2015, às 00:35, mas ele gera como dia 04 às 00:35

**Comment by camponez** [comment]
Esse caso é muito particular e tem a ver com a fato do XML ser gerado usando data GMT e as horas de decolagem e pouso no fuso local.

Esse erro só vai ocorrer quando a ActivityDate estiver com hora entre 2 e 3 horas da manha E estiver no horário de verão.

Não vale a pena corrigir pq quando acabar o horário de verão vai dar erro novamente no caso do horário entre 3 e 4 da manha.
